/**
 * 模块类型统一入口（barrel file）。
 *
 * @description 从 6 个子模块重新导出所有类型，保持对外导入路径不变。
 * 内部文件（composables / core / components）均通过 `../types` 或 `../../types` 导入此 barrel。
 */

export type {
  MaptalksNativeAreaToolOptions,
  MaptalksNativeDistanceToolOptions,
  MaptalksNativeDrawToolOptions,
  MaptalksNativeGeometryOptions,
  MaptalksNativeGLTFLayerOptions,
  MaptalksNativeGroupGLLayerOptions,
  MaptalksNativeInfoWindowOptions,
  MaptalksNativeMapOptions,
  MaptalksNativeMarkerInfoWindowOptions,
  MaptalksNativeTileLayerOptions,
  MaptalksNativeUIMarkerOptions,
  MaptalksNativeVectorLayerOptions,
  MaptalksNativeVectorTileLayerOptions,
  MaptalksNativeWMSTileLayerOptions,
} from './native';

export type {
  LineSymbol,
  MaptalksControl,
  MaptalksCoordinate,
  MaptalksDrawTool,
  MaptalksEventHandler,
  MaptalksGeometry,
  MaptalksGLNamespace,
  MaptalksInfoWindow,
  MaptalksLayer,
  MaptalksMap,
  MaptalksMapTool,
  MaptalksUIMarker,
  MaptalksVectorLayer,
  MaptalksViewLike,
  MarkerSymbol,
  PolygonSymbol,
  Stops,
  SymbolBase,
  TextSymbol,
} from './structural';

export type {
  MaptalksAreaToolOptions,
  MaptalksCircleOptions,
  MaptalksCircleSpecOptions,
  MaptalksDistanceToolOptions,
  MaptalksEllipseOptions,
  MaptalksEllipseSpecOptions,
  MaptalksGeometryBaseOptions,
  MaptalksGeometryBaseSpecOptions,
  MaptalksGLTFLayerOptions,
  MaptalksGLTFLayerSpecOptions,
  MaptalksGroupGLLayerOptions,
  MaptalksGroupGLLayerSpecOptions,
  MaptalksInfoWindowOptions,
  MaptalksInfoWindowSpecOptions,
  MaptalksLabelOptions,
  MaptalksLabelSpecOptions,
  MaptalksLineStringOptions,
  MaptalksLineStringSpecOptions,
  MaptalksMapOptions,
  MaptalksMapSpecOptions,
  MaptalksMarkerInfoWindowOptions,
  MaptalksMarkerOptions,
  MaptalksMarkerSpecOptions,
  MaptalksMultiLineStringOptions,
  MaptalksMultiLineStringSpecOptions,
  MaptalksMultiPointOptions,
  MaptalksMultiPointSpecOptions,
  MaptalksMultiPolygonOptions,
  MaptalksMultiPolygonSpecOptions,
  MaptalksPolygonOptions,
  MaptalksPolygonSpecOptions,
  MaptalksRectangleOptions,
  MaptalksRectangleSpecOptions,
  MaptalksSectorOptions,
  MaptalksSectorSpecOptions,
  MaptalksTextBoxOptions,
  MaptalksTextBoxSpecOptions,
  MaptalksTileLayerOptions,
  MaptalksTileLayerSpecOptions,
  MaptalksUIMarkerOptions,
  MaptalksUIMarkerSpecOptions,
  MaptalksVectorLayerOptions,
  MaptalksVectorLayerSpecOptions,
  MaptalksVectorTileLayerOptions,
  MaptalksVectorTileLayerSpecOptions,
  MaptalksWMSLayerOptions,
  MaptalksWMSLayerSpecOptions,
} from './options';

export type {
  MaptalksDefaults,
  MaptalksError,
  MaptalksErrorCode,
  MaptalksSource,
  ModuleOptions,
  PublicSource,
  ResolvedModuleOptions,
  ResolvedSource,
  SignedSource,
} from './sources';

export type {
  GeoJSONData,
  GeometryPresetBase,
  MaptalksInstanceRef,
  MaptalksSyncField,
  UseMaptalksCameraReturn,
  UseMaptalksCircleOpts,
  UseMaptalksControlReturn,
  UseMaptalksEllipseOpts,
  UseMaptalksExportOpts,
  UseMaptalksExportReturn,
  UseMaptalksGeoJSONOpts,
  UseMaptalksGeoJSONReturn,
  UseMaptalksGeometryOpts,
  UseMaptalksGeometryReturn,
  UseMaptalksGLTFLayerOpts,
  UseMaptalksLabelOpts,
  UseMaptalksLayerControlOpts,
  UseMaptalksLayerControlReturn,
  UseMaptalksLayerOpts,
  UseMaptalksLayerReturn,
  UseMaptalksLineStringOpts,
  UseMaptalksMarkerOpts,
  UseMaptalksMultiLineStringOpts,
  UseMaptalksMultiPointOpts,
  UseMaptalksMultiPolygonOpts,
  UseMaptalksOpts,
  UseMaptalksPolygonOpts,
  UseMaptalksPresetBaseOpts,
  UseMaptalksRectangleOpts,
  UseMaptalksRegistryReturn,
  UseMaptalksReturn,
  UseMaptalksSectorOpts,
  UseMaptalksSourceReturn,
  UseMaptalksSyncOpts,
  UseMaptalksSyncReturn,
  UseMaptalksTextBoxOpts,
  UseMaptalksTileLayerOpts,
  UseMaptalksToolOpts,
  UseMaptalksToolReturn,
  UseMaptalksVectorLayerBaseOpts,
  UseMaptalksVectorLayerOpts,
  UseMaptalksVectorLayerReturn,
  UseMaptalksVectorTileLayerOpts,
  UseMaptalksWMSLayerOpts,
} from './composables';

export type {
  MaptalksGLTFLayerExposed,
  MaptalksGroupGLLayerExposed,
  MaptalksInfoWindowExposed,
  MaptalksLayerExposed,
  MaptalksMapExposed,
  MaptalksMarkerInfoWindowExposed,
  MaptalksTileLayerExposed,
  MaptalksUIMarkerExposed,
  MaptalksVectorLayerExposed,
  MaptalksVectorTileLayerExposed,
  MaptalksWMSLayerExposed,
} from './exposed';
