/**
 * 模块 public API 类型统一导出，供 Nuxt auto-import。
 * 仅包含用户直接使用的入参/出参/Exposed 类型，不含内部实现细节。
 *
 * @description 此文件由 addImportsDir 扫描，类型自动纳入全局补全。
 * 新增 public 类型只需在 `../types/index.ts` 定义后在此补一行。
 *
 * @example
 * // 在 Vue SFC 中直接使用类型（无需手动 import）
 * const opts: UseMaptalksOpts = { center: [121, 31], zoom: 13 };
 * const mapRef: Ref<MaptalksMapExposed | null> = ref(null);
 */
export type {
  // ── 核心结构 ──
  MaptalksAttributionControl,
  MaptalksCircleGeometry,
  MaptalksCompassControl,
  MaptalksControl,
  MaptalksCoordinate,
  MaptalksDrawTool,
  MaptalksEllipseGeometry,
  MaptalksError,
  MaptalksEventHandler,
  MaptalksGeometry,
  MaptalksInfoWindow,
  MaptalksInstanceRef,
  MaptalksLabelGeometry,
  MaptalksLayer,
  MaptalksLineStringGeometry,
  MaptalksMap,
  MaptalksMapTool,
  MaptalksMenu,
  MaptalksMenuItem,
  MaptalksMenuOptions,
  MaptalksMarkerGeometry,
  MaptalksMultiPointGeometry,
  MaptalksPolygonGeometry,
  MaptalksRectangleGeometry,
  MaptalksScaleControl,
  MaptalksSectorGeometry,
  MaptalksSource,
  MaptalksSyncField,
  MaptalksTextBoxGeometry,
  MaptalksToolbarControl,
  MaptalksUIMarker,
  MaptalksZoomControl,
  MaptalksCanvasLayer,
  MaptalksCanvasTileLayer,
  MaptalksGLTFLayer,
  MaptalksGroupGLLayer,
  MaptalksImageLayer,
  MaptalksMultiLineStringGeometry,
  MaptalksMultiPolygonGeometry,
  MaptalksParticleLayer,
  MaptalksTileLayer,
  MaptalksVectorLayer,
  MaptalksVectorTileLayer,
  MaptalksWMSLayer,

  // ── Options ──
  MaptalksAreaToolOptions,
  MaptalksAttributionOptions,
  MaptalksCircleOptions,
  MaptalksCompassOptions,
  MaptalksDistanceToolOptions,
  MaptalksEllipseOptions,
  MaptalksGeometryBaseOptions,
  MaptalksGLTFLayerOptions,
  MaptalksGroupGLLayerOptions,
  MaptalksImageLayerOptions,
  MaptalksInfoWindowOptions,
  MaptalksLabelOptions,
  MaptalksLineStringOptions,
  MaptalksMapOptions,
  MaptalksMarkerOptions,
  MaptalksMultiLineStringOptions,
  MaptalksMultiPointOptions,
  MaptalksMultiPolygonOptions,
  MaptalksPolygonOptions,
  MaptalksRectangleOptions,
  MaptalksScaleOptions,
  MaptalksSectorOptions,
  MaptalksTextBoxOptions,
  MaptalksTileLayerOptions,
  MaptalksToolbarOptions,
  MaptalksUIMarkerOptions,
  MaptalksVectorLayerOptions,
  MaptalksVectorTileLayerOptions,
  MaptalksWMSLayerOptions,
  MaptalksZoomOptions,

  // ── Component Exposed ──
  MaptalksAreaToolExposed,
  MaptalksCircleExposed,
  MaptalksControlExposed,
  MaptalksDistanceToolExposed,
  MaptalksDrawToolExposed,
  MaptalksEllipseExposed,
  MaptalksGeoJSONExposed,
  MaptalksGeometryExposed,
  MaptalksGLTFLayerExposed,
  MaptalksGroupGLLayerExposed,
  MaptalksImageLayerExposed,
  MaptalksInfoWindowExposed,
  MaptalksLabelExposed,
  MaptalksLayerExposed,
  MaptalksLineStringExposed,
  MaptalksMapExposed,
  MaptalksMarkerExposed,
  MaptalksGeometryInfoWindowExposed,
  MaptalksMenuExposed,
  MaptalksMultiLineStringExposed,
  MaptalksMultiPointExposed,
  MaptalksMultiPolygonExposed,
  MaptalksPolygonExposed,
  MaptalksRectangleExposed,
  MaptalksSectorExposed,
  MaptalksTextBoxExposed,
  MaptalksTileLayerExposed,
  MaptalksToolExposed,
  MaptalksUIMarkerExposed,
  MaptalksVectorLayerExposed,
  MaptalksVectorTileLayerExposed,
  MaptalksWMSLayerExposed,

  // ── Composable Options ──
  UseMaptalksAttributionOpts,
  UseMaptalksCircleOpts,
  UseMaptalksCompassOpts,
  UseMaptalksDrawToolOpts,
  UseMaptalksEllipseOpts,
  UseMaptalksExportOpts,
  UseMaptalksGeoJSONOpts,
  UseMaptalksGLTFLayerOpts,
  UseMaptalksImageLayerOpts,
  UseMaptalksGeometryOpts,
  UseMaptalksLabelOpts,
  UseMaptalksLayerControlOpts,
  UseMaptalksLayerOpts,
  UseMaptalksLineStringOpts,
  UseMaptalksMarkerOpts,
  UseMaptalksMultiLineStringOpts,
  UseMaptalksMultiPointOpts,
  UseMaptalksMultiPolygonOpts,
  UseMaptalksOpts,
  UseMaptalksPolygonOpts,
  UseMaptalksPresetBaseOpts,
  UseMaptalksRectangleOpts,
  UseMaptalksScaleOpts,
  UseMaptalksSectorOpts,
  UseMaptalksSyncOpts,
  UseMaptalksTextBoxOpts,
  UseMaptalksTileLayerOpts,
  UseMaptalksToolOpts,
  UseMaptalksVectorLayerBaseOpts,
  UseMaptalksVectorLayerOpts,
  UseMaptalksVectorTileLayerOpts,
  UseMaptalksWMSLayerOpts,
  UseMaptalksZoomOpts,

  // ── Composable Returns ──
  UseMaptalksCameraReturn,
  UseMaptalksControlReturn,
  UseMaptalksDrawToolReturn,
  UseMaptalksExportReturn,
  UseMaptalksGeoJSONReturn,
  UseMaptalksGeometryReturn,
  UseMaptalksLayerControlReturn,
  UseMaptalksLayerReturn,
  UseMaptalksRegistryReturn,
  UseMaptalksReturn,
  UseMaptalksSourceReturn,
  UseMaptalksSyncReturn,
  UseMaptalksToolReturn,
  UseMaptalksVectorLayerReturn,
} from '../types';
