/**
 * 模块 public API 类型统一导出，供 Nuxt auto-import。
 * 仅包含用户直接使用的入参/出参/Exposed 类型，不含内部实现细节。
 *
 * @description 此文件由 addImportsDir 扫描，类型自动纳入全局补全。
 * 新增 public 类型只需在 `../types/index.ts` 定义后在此补一行。
 */
export type {
  // ── 核心结构 ──
  MaptalksControl,
  MaptalksDrawTool,
  MaptalksError,
  MaptalksEventHandler,
  MaptalksGeometry,
  MaptalksInfoWindow,
  MaptalksInstanceRef,
  MaptalksLayer,
  MaptalksMap,
  MaptalksMapTool,
  MaptalksSource,
  MaptalksSyncField,
  MaptalksUIMarker,
  MaptalksVectorLayer,

  // ── Combined options ──
  MaptalksAreaToolCombinedOptions,
  MaptalksCircleCombinedOptions,
  MaptalksDistanceToolCombinedOptions,
  MaptalksEllipseCombinedOptions,
  MaptalksGLTFLayerCombinedOptions,
  MaptalksGroupGLLayerCombinedOptions,
  MaptalksInfoWindowCombinedOptions,
  MaptalksLabelCombinedOptions,
  MaptalksLineStringCombinedOptions,
  MaptalksMarkerCombinedOptions,
  MaptalksMultiLineStringCombinedOptions,
  MaptalksMultiPointCombinedOptions,
  MaptalksMultiPolygonCombinedOptions,
  MaptalksPolygonCombinedOptions,
  MaptalksRectangleCombinedOptions,
  MaptalksSectorCombinedOptions,
  MaptalksTextBoxCombinedOptions,
  MaptalksTileLayerCombinedOptions,
  MaptalksUIMarkerCombinedOptions,
  MaptalksVectorLayerCombinedOptions,
  MaptalksVectorTileLayerCombinedOptions,
  MaptalksWMSTileLayerCombinedOptions,

  // ── Component Exposed ──
  MaptalksGLTFLayerExposed,
  MaptalksGroupGLLayerExposed,
  MaptalksInfoWindowExposed,
  MaptalksLayerExposed,
  MaptalksMapExposed,
  MaptalksMarkerInfoWindowExposed,
  MaptalksTileLayerExposed,
  MaptalksUIMarkerExposed,
  MaptalksVectorLayerExposed,
  MaptalksVectorTileLayerExposed,
  MaptalksWMSLayerExposed,

  // ── Composable Options ──
  UseMaptalksCircleOptions,
  UseMaptalksEllipseOptions,
  UseMaptalksExportOptions,
  UseMaptalksGeoJSONOptions,
  UseMaptalksGLTFLayerOptions,
  UseMaptalksGeomAnimateOptions,
  UseMaptalksGeometryOptions,
  UseMaptalksLabelOptions,
  UseMaptalksLayerControlOptions,
  UseMaptalksLayerOptions,
  UseMaptalksLineStringOptions,
  UseMaptalksMarkerOptions,
  UseMaptalksMoveAlongOptions,
  UseMaptalksMultiLineStringOptions,
  UseMaptalksMultiPointOptions,
  UseMaptalksMultiPolygonOptions,
  UseMaptalksOptions,
  UseMaptalksPolygonOptions,
  UseMaptalksPresetBaseOptions,
  UseMaptalksRectangleOptions,
  UseMaptalksSectorOptions,
  UseMaptalksSyncOptions,
  UseMaptalksTextBoxOptions,
  UseMaptalksTileLayerOptions,
  UseMaptalksToolOptions,
  UseMaptalksVectorLayerBaseOptions,
  UseMaptalksVectorLayerOptions,
  UseMaptalksVectorTileLayerOptions,
  UseMaptalksViewFollowOptions,
  UseMaptalksWMSLayerOptions,

  // ── Composable Returns ──
  UseMaptalksAnimateShowOptions,
  UseMaptalksAnimationReturn,
  UseMaptalksCameraReturn,
  UseMaptalksControlReturn,
  UseMaptalksExportReturn,
  UseMaptalksGeoJSONReturn,
  UseMaptalksGeometryReturn,
  UseMaptalksLayerControlReturn,
  UseMaptalksLayerReturn,
  UseMaptalksRegistryReturn,
  UseMaptalksReturn,
  UseMaptalksSourceReturn,
  UseMaptalksSyncReturn,
  UseMaptalksToolReturn,
  UseMaptalksVectorLayerReturn,
} from '../types';
