/**
 * 模块 public API 类型统一导出，供 Nuxt auto-import。
 * 仅包含用户直接使用的入参/出参/Exposed 类型，不含内部实现细节。
 *
 * @description 此文件由 addImportsDir 扫描，类型自动纳入全局补全。
 * 新增 public 类型只需在 `../types/index.ts` 定义后在此补一行。
 */
export type {
  // ── 核心结构 ──
  MaptalksControl,
  MaptalksDrawTool,
  MaptalksError,
  MaptalksEventHandler,
  MaptalksGeometry,
  MaptalksInfoWindow,
  MaptalksInstanceRef,
  MaptalksLayer,
  MaptalksMap,
  MaptalksMapTool,
  MaptalksSource,
  MaptalksSyncField,
  MaptalksUIMarker,
  MaptalksVectorLayer,

  // ── Options ──
  MaptalksAreaToolOptions,
  MaptalksCircleOptions,
  MaptalksDistanceToolOptions,
  MaptalksEllipseOptions,
  MaptalksGLTFLayerOptions,
  MaptalksGroupGLLayerOptions,
  MaptalksInfoWindowOptions,
  MaptalksLabelOptions,
  MaptalksLineStringOptions,
  MaptalksMarkerOptions,
  MaptalksMultiLineStringOptions,
  MaptalksMultiPointOptions,
  MaptalksMultiPolygonOptions,
  MaptalksPolygonOptions,
  MaptalksRectangleOptions,
  MaptalksSectorOptions,
  MaptalksTextBoxOptions,
  MaptalksTileLayerOptions,
  MaptalksUIMarkerOptions,
  MaptalksVectorLayerOptions,
  MaptalksVectorTileLayerOptions,
  MaptalksWMSLayerOptions,

  // ── Component Exposed ──
  MaptalksGLTFLayerExposed,
  MaptalksGroupGLLayerExposed,
  MaptalksInfoWindowExposed,
  MaptalksLayerExposed,
  MaptalksMapExposed,
  MaptalksMarkerInfoWindowExposed,
  MaptalksTileLayerExposed,
  MaptalksUIMarkerExposed,
  MaptalksVectorLayerExposed,
  MaptalksVectorTileLayerExposed,
  MaptalksWMSLayerExposed,

  // ── Composable Options ──
  UseMaptalksCircleOpts,
  UseMaptalksEllipseOpts,
  UseMaptalksExportOpts,
  UseMaptalksGeoJSONOpts,
  UseMaptalksGLTFLayerOpts,
  UseMaptalksGeometryOpts,
  UseMaptalksLabelOpts,
  UseMaptalksLayerControlOpts,
  UseMaptalksLayerOpts,
  UseMaptalksLineStringOpts,
  UseMaptalksMarkerOpts,
  UseMaptalksMultiLineStringOpts,
  UseMaptalksMultiPointOpts,
  UseMaptalksMultiPolygonOpts,
  UseMaptalksOpts,
  UseMaptalksPolygonOpts,
  UseMaptalksPresetBaseOpts,
  UseMaptalksRectangleOpts,
  UseMaptalksSectorOpts,
  UseMaptalksSyncOpts,
  UseMaptalksTextBoxOpts,
  UseMaptalksTileLayerOpts,
  UseMaptalksToolOpts,
  UseMaptalksVectorLayerBaseOpts,
  UseMaptalksVectorLayerOpts,
  UseMaptalksVectorTileLayerOpts,
  UseMaptalksWMSLayerOpts,

  // ── Composable Returns ──
  UseMaptalksCameraReturn,
  UseMaptalksControlReturn,
  UseMaptalksExportReturn,
  UseMaptalksGeoJSONReturn,
  UseMaptalksGeometryReturn,
  UseMaptalksLayerControlReturn,
  UseMaptalksLayerReturn,
  UseMaptalksRegistryReturn,
  UseMaptalksReturn,
  UseMaptalksSourceReturn,
  UseMaptalksSyncReturn,
  UseMaptalksToolReturn,
  UseMaptalksVectorLayerReturn,

  // test
  MaptalksNativeVectorLayerOptions,
  MaptalksNativeMapOptions,
} from '../types';
